name: New contributor profile
description: Issue ticket for introducing oneself as a potential project contributor
title:  "{Your Name}: Dev Contributor Profile"
labels: [ "devs", "contributor profile"]
assignees:
  - jcklpe
body:
  - type: textarea
    id: introduction
    attributes:
      label: Introduction
      description: Brief introduction of who you are and your interest in Open Austin
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: what-i-know
    attributes:
      label: What I know
      description: List in bullet point form your skills. This can include programming languages, frameworks, development methodologies, version control tools, and software used in your development workflow.
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: what-i-want-to-know
    attributes:
      label: What I want to know
      description: What are somethings you'd like to gain more experience with?
      placeholder:
      value:
    validations:
      required: true
